theme: jekyll-theme-minimal
title: Yanou Ramon
logo: /img/profile.png
name: Yanou Ramon
description: "Applied Data Mining (ADM) Research Group, University of Antwerp.\n 
              Department of Engineering Management.\n 
              City Campus, B-building (Room B.513)."
