theme: jekyll-theme-minimal
title: Yanou Ramon
name: Yanou Ramon
description: "Applied Data Mining (ADM) Research Group, University of Antwerp <\b> Department of Engineering Management <\b> City Campus, B-building (room B.508)"
