theme: jekyll-theme-minimal
title: Yanou Ramon
name: Yanou Ramon
description: "Applied Data Mining (ADM) Research Group, University of Antwerp. Department of Engineering Management. City Campus, B-building (room B.508)"
