theme: jekyll-theme-minimal
title: Yanou Ramon
logo: /img/yanou3.png
name: Yanou Ramon
description: "Applied Data Mining Research Group, University of Antwerp, Belgium.\n 
              Department of Engineering Management.\n 
              City Campus, B-building (Room B.513)."
